project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

website:
  title: "Phu Vo"
  navbar:
      left:
      - href: index.qmd
        text: Home

      - text: Data Visualization
        menu:
          - text: "Eurovision Song Contest"
            href: dveu.html

          - text: "Spotify"
            href: dvspot.html
      
      - href: Dickinson.html
        text: Full Text Analysis
        
      - href: AnimalCrossing.html
        text: Permutation Testing
        
      - href: project4.html
        text: Ethics
        
      - href: project5.html
        text: SQL 
        
      - href: p1.html
        text: Practice
            
format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

